### ISSUE TITLE
Does this work with babel6 ?

### ISSUE THREAD

**Issue by riston** [megawac/babel-plugin-ramda#3]
I am getting an error with babel6, the lodash version seems to be working great. I haven't diffed the changes between code base.

```
TypeError: Plugin is not a function
    at exports.default (/home/risto/my-app-name-here/node_modules/babel-plugin-ramda/lib/index.js:33:10)
    at Function.memoisePluginContainer (/home/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:1
27:13)
    at Function.normalisePlugin (/home/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:32)
    at /home/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:197:30
    at Array.map (native)
    at Function.normalisePlugins (/home/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/home/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36
)
    at OptionManager.mergeOptions (/home/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:303:10
)
    at OptionManager.addConfig (/home/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/home/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)

```

**Comment by megawac** [comment]
Needs to be updated for babel 6, I'll do it this weekend.

**Comment by borisirota** [comment]
Hi, very useful plugin. Thanks !

Any estimation when it will ready ? :)
