### ISSUE TITLE
Troubles with wildcard exports of ES6

### ISSUE THREAD

**Issue by ctrlplusb** [megawac/babel-plugin-ramda#7]
Hi; this one is baffling me.

I have code like such, which imports modules using ramda.
```
export * from './foo'
```

When running babel over my code with this plugin it fails with the following errors:
```
Cannot read property 'file' of undefined
    at PluginPass.Identifier (/code/test/ramda-plugin-fix/node_modules/babel-plugin-ramda/lib/index.js:80:23)
    at newFn (/code/test/ramda-plugin-fix/node_modules/babel-traverse/lib/visitors.js:293:19)
    at NodePath._call (/code/test/ramda-plugin-fix/node_modules/babel-traverse/lib/path/context.js:75:18)
    at NodePath.call (/code/test/ramda-plugin-fix/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/code/test/ramda-plugin-fix/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/code/test/ramda-plugin-fix/node_modules/babel-traverse/lib/context.js:156:16)
    at TraversalContext.visitSingle (/code/test/ramda-plugin-fix/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/code/test/ramda-plugin-fix/node_modules/babel-traverse/lib/context.js:200:19)
    at Function.traverse.node (/code/test/ramda-plugin-fix/node_modules/babel-traverse/lib/index.js:141:17)
    at NodePath.visit (/code/test/ramda-plugin-fix/node_modules/babel-traverse/lib/path/context.js:115:22)
```

I forked your repo and included a test specifically for this use case, but no errors whilst running the tests.  I thought perhaps another babel plugin or dependency may be causing the issue.  So then I created a super simple project with no other dependencies but when running the project it fell over immediately.  Very peculiar.

I have included the project I created in this link: https://www.dropbox.com/s/qc99y5578o46860/ramda-plugin-fix.zip?dl=0

It's using node 4.3.1 and npm 3.7.3 as specified in the package.json file.

If you do an `npm install && npm run build` you'll see the error.

**Comment by megawac** [comment]
Thanks for the report. I'll investigate tomorrow

**Comment by megawac** [comment]
I haven't been able to reproduce the bug. I placed the repro case in a github repo (https://github.com/megawac/babel-plugin-ramda-issue-7) if you want to try and modify it to error

**Comment by ctrlplusb** [comment]
Sorry, been away on holiday - hence delayed reply to this.

Thank you kindly for taking the time to investigate.  I'll try and update my babel instances and report back with results.
